services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: db_admin
      POSTGRES_PASSWORD: aHmcgvbQEIEWWXwWFGLp26OwwsxQLiWA
      POSTGRES_DB: app
    ports:
      - "13001:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nextjs-app:
    build:
      context: ./telapo
      dockerfile: Dockerfile
    ports:
      - "13000:3000"
    volumes:
      - ./telapo:/app
      - /app/node_modules
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5432
    depends_on:
      - postgres

volumes:
  postgres_data:
